export const uniLevelTableRowData = [
    {
        "S/N": "1",
        "User ID": "ROBO043733",
        "User Name": "Mahesh Rai",
        "Amount": "0",
        "Status": "Inactive",
        "Direct Team": "0",
        "Direct Business": "0",
        "Team Business": "0",
        "Rank": "NA",
        "Joined on": "22-04-2023",
        "Top uped on": "22-04-2023"
    },
    {
        "S/N": "1",
        "User ID": "ROBO043733",
        "User Name": "Mahesh Rai",
        "Amount": "0",
        "Status": "Inactive",
        "Direct Team": "0",
        "Direct Business": "0",
        "Team Business": "0",
        "Rank": "NA",
        "Joined on": "22-04-2023",
        "Top uped on": "22-04-2023"
    },
    {
        "S/N": "1",
        "User ID": "ROBO043733",
        "User Name": "Mahesh Rai",
        "Amount": "0",
        "Status": "Inactive",
        "Direct Team": "0",
        "Direct Business": "0",
        "Team Business": "0",
        "Rank": "NA",
        "Joined on": "22-04-2023",
        "Top uped on": "22-04-2023"
    },
    {
        "S/N": "1",
        "User ID": "ROBO043733",
        "User Name": "Mahesh Rai",
        "Amount": "0",
        "Status": "Inactive",
        "Direct Team": "0",
        "Direct Business": "0",
        "Team Business": "0",
        "Rank": "NA",
        "Joined on": "22-04-2023",
        "Top uped on": "22-04-2023"
    },
    {
        "S/N": "1",
        "User ID": "ROBO043733",
        "User Name": "Mahesh Rai",
        "Amount": "0",
        "Status": "Inactive",
        "Direct Team": "0",
        "Direct Business": "0",
        "Team Business": "0",
        "Rank": "NA",
        "Joined on": "22-04-2023",
        "Top uped on": "22-04-2023"
    },
    {
        "S/N": "1",
        "User ID": "ROBO043733",
        "User Name": "Mahesh Rai",
        "Amount": "0",
        "Status": "Inactive",
        "Direct Team": "0",
        "Direct Business": "0",
        "Team Business": "0",
        "Rank": "NA",
        "Joined on": "22-04-2023",
        "Top uped on": "22-04-2023"
    },
    {
        "S/N": "1",
        "User ID": "ROBO043733",
        "User Name": "Mahesh Rai",
        "Amount": "0",
        "Status": "Inactive",
        "Direct Team": "0",
        "Direct Business": "0",
        "Team Business": "0",
        "Rank": "NA",
        "Joined on": "22-04-2023",
        "Top uped on": "22-04-2023"
    },
    {
        "S/N": "1",
        "User ID": "ROBO043733",
        "User Name": "Mahesh Rai",
        "Amount": "0",
        "Status": "Inactive",
        "Direct Team": "0",
        "Direct Business": "0",
        "Team Business": "0",
        "Rank": "NA",
        "Joined on": "22-04-2023",
        "Top uped on": "22-04-2023"
    },
    {
        "S/N": "1",
        "User ID": "ROBO043733",
        "User Name": "Mahesh Rai",
        "Amount": "0",
        "Status": "Inactive",
        "Direct Team": "0",
        "Direct Business": "0",
        "Team Business": "0",
        "Rank": "NA",
        "Joined on": "22-04-2023",
        "Top uped on": "22-04-2023"
    },
    {
        "S/N": "1",
        "User ID": "ROBO043733",
        "User Name": "Mahesh Rai",
        "Amount": "0",
        "Status": "Inactive",
        "Direct Team": "0",
        "Direct Business": "0",
        "Team Business": "0",
        "Rank": "NA",
        "Joined on": "22-04-2023",
        "Top uped on": "22-04-2023"
    },
]
